const constants = {
    //I18n
    I18N_WORD_UPDATE: "I18N_WORD_UPDATE",
    I18n_WORDS_UPDATE: "I18N_WORDS_UPDATE",

    //User
    USER_UPDATE: "USER_UPDATE",
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",

    //Contacts
    CONTACTS_REFRESH: "CONTACTS_REFRESH",
    CONTACTS_DELETE_CONTACT: "CONTACTS_DELETE_CONTACT",
    CONTACTS_NEW_CONTACT: "CONTACTS_NEW_CONTACT",

    //Config
    CONFIG_NEW_SERVER_ROOT: "CONFIG_NEW_SERVER_ROOT",

    //Rooms
    ROOMS_NEW_ROOMS: "ROOMS_NEW_ROOMS",
    ROOMS_NEW_ROOM: "ROOMS_NEW_ROOM",
    ROOMS_EXIT_ROOM: "ROOMS_EXIT_ROOM",
    ROOMS_NEW_ACTIVE_ROOM: "ROOMS_NEW_ACTIVE_ROOM",

    //Sidebar
    SIDEBAR_TOGGLE: "SIDEBAR_TOGGLE",

    //Messages
    MESSAGE_TEXT_MESSAGE: "TEXT_MESSAGE",
    MESSAGE_USER_CONNECTED: "MESSAGE_USER_CONNECTED",
    MESSAGE_USER_DISCONNECTED: "MESSAGE_USER_DISCONNECTED",
    MESSAGE_VIDEO_CALL_START: "VIDEO_MESSAGE_START",
    MESSAGE_VIDEO_CALL_END: "VIDEO_MESSAGE_STOP",
    MESSAGE_AUTHENTICATE: "AUTHENTICATE",
    MESSAGE_UNAUTHENTICATED: "UNAUTHENTICATED",
    MESSAGE_WELCOME: "WELCOME",
    MESSAGE_ERROR: "ERROR",
    MESSAGE_ACKNOWLEDGE: "SUCCESS",
    MESSAGE_DISCONNECTED: "MESSAGE_DISCONNECTED",
    MESSAGE_REFRESH_ROOMS: "REFRESH_ROOMS"
};
export default constants;
