const constants = {
    NEW_SERVER_ROOT: "NEW_SERVER_ROOT",
    USER_SELECTED: "USER_SELECTED",
    REFRESH_CONTACTS: "REFRESH_CONTACTS",
    NEW_NOTIFY: "NEW_NOTIFY",
    NEW_USER_NAME: "NEW_USER_NAME",
    ADD_USER: "ADD_USER"
};
export default constants;
