const constants = {
    NEW_NOTIFY: "NEW_NOTIFY",
    NEW_USER_NAME: "NEW_USER_NAME",
    ADD_USER: "ADD_USER",
    DELETE_USER: "DELETE_USER",
    STOP_VIDEO: "STOP_VIDEO",
    CLOSE_SOCKET: "CLOSE_SOCKET",
    VIDEO_MESSAGE: "VIDEO_MESSAGE",
    TEXT_MESSAGE: "TEXT_MESSAGE",
    DELETE_NOTIFY: "DELETE_NOTIFY",
    CREATE_NOTIFY: "CREATE_NOTIFY",
    TOGGLE_STATE: "TOGGLE_STATE",
    REFRESH_SELECT: "REFRESH_SELECT",
    VIDEO_CALL_START: "VIDEO_CALL_START",
    VIDEO_CALL_END: "VIDEO_CALL_END",
    DELETED_CONTACT: "DELETED_CONTACT",


    //I18n
    I18N_WORD_UPDATE: "I18N_WORD_UPDATE",
    I18n_WORDS_UPDATE: "I18N_WORDS_UPDATE",

    //User
    USER_UPDATE: "USER_UPDATE",
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",

    //Contacts
    CONTACTS_REFRESH: "CONTACTS_REFRESH",
    CONTACTS_DELETE_CONTACT: "CONTACTS_DELETE_CONTACT",
    CONTACTS_NEW_CONTACT: "CONTACTS_NEW_CONTACT",

    //Config
    CONFIG_NEW_SERVER_ROOT: "CONFIG_NEW_SERVER_ROOT",

    //Rooms
    ROOMS_NEW_MESSAGE: "ROOMS_NEW_MESSAGE",
    ROOMS_NEW_ROOMS: "ROOMS_NEW_ROOMS",
    ROOMS_NEW_ROOM: "ROOMS_NEW_ROOM",
    ROOMS_DELETE_ROOM: "ROOMS_DELETE_ROOM",
    ROOMS_NEW_ACTIVE_ROOM: "ROOMS_NEW_ACTIVE_ROOM",

    //Sidebar
    SIDEBAR_TOGGLE: "SIDEBAR_TOGGLE",

    //Messages
    MESSAGE_TEXT_MESSAGE: "TEXT_MESSAGE",
    MESSAGE_USER_CONNECTED: "MESSAGE_USER_CONNECTED",
    MESSAGE_USER_DISCONNECTED: "MESSAGE_USER_DISCONNECTED",
    MESSAGE_VIDEO_CALL_START: "MESSAGE_VIDEO_CALL_START",
    MESSAGE_VIDEO_CALL_END: "MESSAGE_VIDEO_CALL_END"
};
export default constants;
